---
version: 2

jobs:
  test:
    docker:
    - image: circleci/golang:1.11

    steps:
    - checkout
    - run: make promu
    - run: make style build
    - run: rm -fv kamailio_exporter

  build:
    machine: true

    steps:
    - checkout
    - run: make promu
    - run: promu crossbuild -v
    - persist_to_workspace:
        root: .
        paths:
        - .build
    - store_artifacts:
        path: .build
        destination: /build

workflows:
  version: 2
  kamailio_exporter:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - build:
        filters:
          tags:
            only: /^v\d+\.\d+\.\d+$/
